sudo: required
language: minimal
services:
  - docker

env:
 - IMAGE_PATH=wikibase/1.32/
 - IMAGE_PATH=wikibase/1.31/
 - IMAGE_PATH=wdqs/0.2.5/
 - IMAGE_PATH=wdqs/0.3.0/
 - IMAGE_PATH=wdqs/0.3.1/
 - IMAGE_PATH=wdqs-frontend/latest/
 - IMAGE_PATH=wdqs-proxy/latest/
 - IMAGE_PATH=quickstatements/latest/

script:
 - source ./.travis/docker-push-setup.sh
 - source ./.travis/docker-build-common.sh
 - bash ./$IMAGE_PATH/.travis/build-deploy.sh

jobs:
  include:
    - stage: prebuild
      script: bash ./.travis/checkx.sh
      env:
       - SCRIPT=checkx
       - IMAGE_PATH=all
    - stage: prebuild
      script: bash ./.travis/run-linters.sh
      env:
       - SCRIPT=hadolint
       - IMAGE_PATH=all

stages:
  - prebuild
  - test
