# Wikibase with Query Service
#
# Access Wikibase via "http://localhost:8181"
#   (or "http://$(docker-machine ip):8181" if using docker-machine)
#
# Access Query Service via "http://localhost:8282"
#   (or "http://$(docker-machine ip):8282" if using docker-machine)
version: '3'

services:
  wikibase:
    image: wikibase/wikibase
    restart: always
    build:
      context: ./wikibase
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
     - "8181:80"
    volumes:
      - mediawiki-images-data:/var/www/html/images
    depends_on:
    - mysql
    networks:
      default:
        aliases:
         - wikibase.svc
  mysql:
    image: mariadb
    restart: always
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  wdqs-frontend:
    image: wikibase/wdqs-frontend
    restart: always
    build:
      context: ./wdqs-frontend
      dockerfile: Dockerfile
    environment:
     - LANGUAGE=en
     - BRAND_TITLE=LocalDockerQuery
     - SPARQL_URI=/proxy/wdqs/bigdata/namespace/wdq/sparql
     - WIKIBASE_API=/proxy/wikibase/w/api.php
    ports:
     - "8282:80"
    depends_on:
    - wdqs-proxy
  wdqs:
    image: wikibase/wdqs
    restart: always
    build:
      context: ./wdqs
      dockerfile: Dockerfile
    volumes:
      - query-service-data:/wdqs/data
  wdqs-proxy:
    image: wikibase/wdqs-proxy
    restart: always
    build:
      context: ./wdqs-proxy
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS_HOST=wdqs:9999
    ports:
     - "8989:80"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/wdqs.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
    - wdqs
  wdqs-updater:
    image: wikibase/wdqs-updater
    restart: always
    build:
      context: ./wdqs-updater
      dockerfile: Dockerfile
    depends_on:
    - wdqs
    - wikibase

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data: